# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # ON REMPLACE "session: true" PAR CE BLOC :
    session:
        enabled: true
        handler_id: null
        cookie_httponly: true
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 3600
        cookie_lifetime: 3600

    # On laisse le reste tel quel
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file