security:
    # 1. Hachage des mots de passe (Mission 1.1)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Hiérarchie des rôles (Mission 4.1)
    # L'admin a tous les droits, le vendeur a ses droits + ceux d'un utilisateur classique
    role_hierarchy:
        ROLE_SELLER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_SELLER, ROLE_USER]

    # 3. Chargement des utilisateurs (Mission 1.1)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            
            # Gestion de la déconnexion (Mission 2.2)
            logout:
                path: app_logout
                target: app_login

            # Option pour rester connecté (Mission 8)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /

    # 4. Protection des routes (Mission 5.1 & 6.1)
    access_control:
        # Routes Admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Routes Vendeur (Protégées par ROLE_SELLER)
        - { path: ^/artisan, roles: ROLE_SELLER }
        - { path: ^/seller, roles: ROLE_SELLER }

        # Routes Client Connecté
        - { path: ^/commande, roles: ROLE_USER }
        - { path: ^/checkout, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }

        # Routes Publiques
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/product, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10