security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_SELLER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_SELLER, ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            
            logout:
                path: app_logout
                target: app_home # Rediriger vers l'accueil est plus sympa après déco

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # 1. ADMIN : Priorité haute
        - { path: ^/admin, roles: ROLE_ADMIN }

        # 2. ACTIONS PRODUITS SENSIBLES (New, Edit, Delete)
        # On force la connexion pour ces actions spécifiques
        - { path: ^/product/(new|edit|delete), roles: ROLE_SELLER }

        # 3. ROUTES VENDEURS
        - { path: ^/artisan, roles: ROLE_SELLER }
        - { path: ^/seller, roles: ROLE_SELLER }

        # 4. ROUTES CLIENTS
        - { path: ^/commande, roles: ROLE_USER }
        - { path: ^/cart, roles: ROLE_USER } # Ajouté pour sécuriser le panier
        - { path: ^/profile, roles: ROLE_USER }

        # 5. PUBLIC : Tout le reste
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/product, roles: PUBLIC_ACCESS } # La liste et le détail restent publics
        - { path: ^/$, roles: PUBLIC_ACCESS }